app/user/models.py
# -- coding: utf-8 --
import json
from app.api.firebase import FirebaseModel


class User(FirebaseModel):
    
    def __init__(self, name, email, phone=None, address=None, pic=None):
        self.name = name
        self.email = email
        self.phone = phone
        self.address = address
        self.pic = pic
        super().__init__()

    def __repr__(self):
        return '<User %r>' % self.name

    def toJSON(self):
        """ 
        Returns a JSON string from the current object 
        """
        return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)

app/user/forms.py
# -- coding: utf-8 --
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import Required, Email


class RegisterForm(Form):
    name = StringField('Name', validators=[Required()])
    email = StringField('Email', validators=[Required(), Email()])
    phone = StringField('Phone', validators=[Required()])
    address = StringField('Address', validators=[Required()])

app/app.py
# -- coding: utf-8 --
"""
Module containing the app initialization statements
"""

from flask import Flask
from .home.controllers import home
from .user.controllers import user
from .googleauth.controllers import googleauth

app = Flask(__name__, instance_relative_config=True)
app.register_blueprint(home)
app.register_blueprint(user)
app.register_blueprint(googleauth)

# Load the default configuration
app.config.from_object('config.default')

# Load the configuration from the instance folder
#app.config.from_pyfile('config.py')

try:
    # Load the file specified by the APP_CONFIG_FILE environment variable
    # Variables defined here will override those in the default configuration
    app.config.from_envvar('APP_CONFIG_FILE')
except:
    pass

app/googleauth/controllers.py
import json
import flask
from oauth2client import client

googleauth = flask.Blueprint('googleauth', __name__)


@googleauth.route('/oauth2callback')
def oauth2callback():
    """ This controller handles the callback url for oauth """

    # create a flow object. It doesn't provide any api access itself, though it's used to go through
    # the steps required for access granting.
    flow = client.flow_from_clientsecrets(
        flask.current_app.config['GOOGLE_CLI_SCRETS'],
        scope=flask.current_app.config['GOOGLE_CLI_SCOPE'],
        redirect_uri=flask.url_for(
            'googleauth.oauth2callback', _external=True
        ),
    )
    flow.params['access_type'] = 'offline'
    flow.params['include_granted_scopes'] = 'true' # boolean must be string.

    # Check if the authorization code is not already in the url. Meaning that user hasn't seen
    # the authorization interface yet. If that's the case we should take him there by redirecting
    # him so he can provide us the authorization code.
    if 'code' not in flask.request.args:
        auth_uri = flow.step1_get_authorize_url() # first step of the flow. Almost there :)
        return flask.redirect(auth_uri)
    else:
        # Once we have the authorization code we use it to retrieve the credentials needed to
        # perform api calls on the user's behaf. Credentials are, the, set to session.
        auth_code = flask.request.args.get('code')
        credentials = flow.step2_exchange(auth_code)
        flask.session['credentials'] = credentials.to_json()

        # Going back to the login :)
        return flask.redirect(flask.url_for('user.login'))

app/home/controllers.py
# -- coding: utf-8 --
import json
import flask
from flask import current_app
from app.user.models import User

home = flask.Blueprint('home', __name__)

@home.route('/')
def index():
    user = None
    users = []
    if flask.session.get('user', None):
        user_json = json.loads(flask.session.get('user', ''))
        user = User.filter(email=user_json.get('email')).first()
        if not user:
            return flask.redirect(flask.url_for('user.login'))
        users = User.all().excludes(email=user.email)
    return flask.render_template('index.html', user=user, users=users)

app/user/controllers.py
# -- coding: utf-8 --
from oauth2client import client
import httplib2
from apiclient import discovery
import json
import flask
from flask import request
from .forms import RegisterForm
from .models import User

user = flask.Blueprint('user', __name__)


@user.route('/login', methods=["GET", "POST"])
def login():
    """ This is the first endpoint of the authentication process """

    # Check whether or not the user has already been through the oauth authorization screen.
    # If not, than he is redirected to the oauth process.
    if 'credentials' not in flask.session:
        return flask.redirect(flask.url_for('googleauth.oauth2callback'))

    credentials = client.OAuth2Credentials.from_json(
        flask.session['credentials']
    )

    # Even if the user had been through authorization screen once, it might have expired.
    # In that casekick him back there!
    if credentials.access_token_expired:
        # If the credentials are expired, get them .
        return flask.redirect(flask.url_for('googleauth.oauth2callback'))
    else:
        # Now that we've got the credentials to act on user's behalf, we can finally build the api
        # object to perform api calls.
        http_auth = credentials.authorize(httplib2.Http())
        # the api object itself.
        drive = discovery.build('drive', 'v2', http_auth)

        # runing the api calls.
        about = drive.about().get().execute()  # Get about properties of Drive object
        # Get profile properties from authorized used
        profile = about.get('user')

        # Check if the user is already registered, by querying it's e-mail to the database.
        user = User.filter(email = profile.get('emailAddress')).first()
        if not user:
            user = User(
                name = profile.get('displayName'),
                email = profile.get('emailAddress'),
                pic = profile.get('picture').get('url') if profile.get('picture') else ''
            )
            flask.session['user'] = user.toJSON()
            form = RegisterForm(request.form)
            if request.method == 'GET':
                form = RegisterForm(obj=user)
                return flask.render_template('user/register.html', form=form, user=user)
            if form.validate_on_submit():
                user = User(
                    name = form.name.data,
                    email = form.email.data,
                    phone = form.phone.data,
                    address = form.address.data,
                    pic = profile.get('picture').get('url') if profile.get('picture') else ''
                )
                user.save()
            else:
                return flask.render_template('user/register.html', form=form, user=user)
        flask.session['user'] = user.toJSON()
        return flask.redirect(flask.url_for('home.index'))


@user.route('/logout')
def logout():
    credentials = client.OAuth2Credentials.from_json(flask.session['credentials'])
    try:
        credentials.revoke(httplib2.Http())
    except:
        pass
    flask.session.clear()
    return flask.redirect(flask.url_for('home.index'))


@user.route('/update/<user_id>', methods=["GET", "POST"])
def update(user_id):
    user = User.get_by_id(user_id)
    form = RegisterForm(request.form)
    if request.method == 'GET':
        form = RegisterForm(obj=user)
        return flask.render_template('user/register.html', form=form, user=user)
    if form.validate_on_submit():
        user = User(
            name = form.name.data,
            email = form.email.data,
            phone = form.phone.data,
            address = form.address.data,
            pic = user.pic
        )
        user.id = user_id
        user.save()
    flask.session['user'] = user.toJSON()
    return flask.redirect(flask.url_for('home.index'))

app/templates/index.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <!-- Global Site Tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-107296719-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments)};
            gtag('js', new Date());
            gtag('config', 'UA-107296719-1');
        </script>

        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}?v={{ range(1, 100000000000) | random }}">
    </head>
    <body>
        {% if not session.user %}
            <div class="blur-fullscreen"></div>
            <div class="login">
                <div><img src="{{ url_for('static', filename='img/photo.png') }}" alt=""></div>
                <div>
                    <form action="{{ url_for('user.login') }}">
                        <button class="loginBtn loginBtn--google">
                            Login with Google
                        </button>
                    </form>
                </div>
            </div>
        {% else %}
            <div class="header">
                <img class="you" src="{{
                    user.pic if user.pic else url_for('static', filename='img/dummy-profile-pic.png') 
                }}?sz=250" alt="">
            </div>
            <div class="widget">
                <div class="blur"></div>
                <div class="text">
                    {% block textcenter %}
                    <h1 class="">Hi, {{ user.name }}</h1>
                    <p>You are registered at SheetGo.</p>
                    <div class="actions">
                        <a href="{{url_for('user.logout')}}">Logout!</a>
                        <a href="{{url_for('user.update', user_id=user.id)}}">Edit your profile!</a>
                    </div>
                    {% endblock %}
                </div>
            </div>
            {% block content %}
            <div class="content">
                <h2>Check out who else is here.</h2>
                <div class="container">
                    {% for userModel in users %}
                    <div class="user">
                        <img src="{{
                            userModel.pic if userModel.pic else url_for('static', filename='img/dummy-profile-pic.png') 
                        }}?sz=250" alt="">
                        <h3>{{ userModel.name }}</h3>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endblock %}
        {% endif %}
    </body>
</html>

app/templates/user/register.html
{% extends "index.html" %}

{% block textcenter %}
<h1 class="">Editing profile info for {{ user.name }}</h1>
{% endblock %}

{% block content %}
    <div class="content register">
        <form action="{{ request.path }}" method="post">
            <div>
                <label for="name">Name:
                    {% for error in form.errors.name %}
                    <div class="alert error">
                        {{ error }}, 
                    </div>
                    {% endfor %}
                </label>
                {{ form.name }}
            </div>

            <div>
                <label for="email">email:
                    {% for error in form.errors.email %}
                    <div class="alert error">
                        {{ error }}, 
                    </div>
                    {% endfor %}
                </label>
                {{ form.email(readonly=true) }}
            </div>

            <div>
                <label for="phone">Phone:
                    {% for error in form.errors.phone %}
                    <div class="alert error">
                        {{ error }}, 
                    </div>
                    {% endfor %}
                </label>
                {{ form.phone }}
            </div>

            <div>
                <label for="phone">Address:
                    {% for error in form.errors.address %}
                    <div class="alert error">
                        {{ error }}, 
                    </div>
                    {% endfor %}
                </label>
                {{ form.address }}
            </div>

            <input type="submit" value="Register!">
            
            {{ form.csrf_token }}
        </form>
    </div>
{% endblock %}